<?php

use App\Models\Location\City;
use App\Models\Location\Country;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    //consider using the following json file for a full list of airports
    //https://raw.githubusercontent.com/jbrooksuk/JSON-Airports/master/airports.json
    protected $cities = [
        ["city" => "Al Arish", "country_code" => "EG"],
        ["city" => "Aalborg", "country_code" => "DK"],
        ["city" => "Mala Mala", "country_code" => "ZA"],
        ["city" => "Al Ain", "country_code" => "AE"],
        ["city" => "Anapa", "country_code" => "RU"],
        ["city" => "Aarhus", "country_code" => "DK"],
        ["city" => "Abakan", "country_code" => "RU"],
        ["city" => "Albacete", "country_code" => "ES"],
        ["city" => "Allentown", "country_code" => "US"],
        ["city" => "Abidjan", "country_code" => "CI"],
        ["city" => "Bamaga", "country_code" => "AU"],
        ["city" => "Albuquerque", "country_code" => "US"],
        ["city" => "Abuja", "country_code" => "NG"],
        ["city" => "Albury", "country_code" => "AU"],
        ["city" => "Aberdeen", "country_code" => "GB"],
        ["city" => "Acapulco", "country_code" => "MX"],
        ["city" => "Accra", "country_code" => "GH"],
        ["city" => "Lanzarote", "country_code" => "ES"],
        ["city" => "Eureka Arcata", "country_code" => "US"],
        ["city" => "Addis Ababa", "country_code" => "ET"],
        ["city" => "Aden", "country_code" => "YE"],
        ["city" => "Adak Island", "country_code" => "US"],
        ["city" => "Adelaide", "country_code" => "AU"],
        ["city" => "Adelaide", "country_code" => "AU"],
        ["city" => "Kodiak", "country_code" => "US"],
        ["city" => "San Andres", "country_code" => "CO"],
        ["city" => "Sochi", "country_code" => "RU"],
        ["city" => "Alexandria", "country_code" => "US"],
        ["city" => "Agadir", "country_code" => "MA"],
        ["city" => "Malaga", "country_code" => "ES"],
        ["city" => "Augusta", "country_code" => "US"],
        ["city" => "Ciudad Del Este", "country_code" => "PY"],
        ["city" => "Abha", "country_code" => "SA"],
        ["city" => "Alghero", "country_code" => "IT"],
        ["city" => "Aracaju", "country_code" => "BR"],
        ["city" => "Asahikawa", "country_code" => "JP"],
        ["city" => "Auckland", "country_code" => "NZ"],
        ["city" => "King Salmon", "country_code" => "US"],
        ["city" => "Almaty", "country_code" => "KZ"],
        ["city" => "Albany (US)", "country_code" => "US"],
        ["city" => "Alicante", "country_code" => "ES"],
        ["city" => "Algiers", "country_code" => "DZ"],
        ["city" => "Albany", "country_code" => "AU"],
        ["city" => "Waterloo", "country_code" => "US"],
        ["city" => "Aleppo", "country_code" => "SY"],
        ["city" => "Alenquer", "country_code" => "BR"],
        ["city" => "Walla Walla", "country_code" => "US"],
        ["city" => "Alexandria", "country_code" => "EG"],
        ["city" => "Amarillo", "country_code" => "US"],
        ["city" => "Ahmedabad", "country_code" => "IN"],
        ["city" => "Amman (Marka)", "country_code" => "JO"],
        ["city" => "Amman", "country_code" => "JO"],
        ["city" => "Ambon", "country_code" => "ID"],
        ["city" => "Amsterdam (Railway)", "country_code" => "NL"],
        ["city" => "Amsterdam", "country_code" => "NL"],
        ["city" => "Anchorage", "country_code" => "US"],
        ["city" => "Antofagasta", "country_code" => "CL"],
        ["city" => "Ankara", "country_code" => "TR"],
        ["city" => "Antigua", "country_code" => "AG"],
        ["city" => "Aomori", "country_code" => "JP"],
        ["city" => "Karpathos", "country_code" => "GR"],
        ["city" => "Alor Setar", "country_code" => "MY"],
        ["city" => "Napa", "country_code" => "US"],
        ["city" => "Apartado", "country_code" => "CO"],
        ["city" => "Apia", "country_code" => "WS"],
        ["city" => "Aqaba", "country_code" => "JO"],
        ["city" => "Arequipa", "country_code" => "PE"],
        ["city" => "Arica", "country_code" => "CL"],
        ["city" => "Armidale", "country_code" => "AU"],
        ["city" => "Watertown", "country_code" => "US"],
        ["city" => "Ashkhabad", "country_code" => "TM"],
        ["city" => "Aspen", "country_code" => "US"],
        ["city" => "Astrakan", "country_code" => "RU"],
        ["city" => "Alice Springs", "country_code" => "AU"],
        ["city" => "Asuncion", "country_code" => "PY"],
        ["city" => "Athens (Hellinikon)", "country_code" => "GR"],
        ["city" => "Athens", "country_code" => "GR"],
        ["city" => "Atlanta", "country_code" => "US"],
        ["city" => "Amritsar", "country_code" => "IN"],
        ["city" => "Appleton", "country_code" => "US"],
        ["city" => "Aruba", "country_code" => "AW"],
        ["city" => "Abu Dhabi", "country_code" => "AE"],
        ["city" => "Austin", "country_code" => "US"],
        ["city" => "Wausau", "country_code" => "US"],
        ["city" => "Asheville", "country_code" => "US"],
        ["city" => "Wilkes Barre", "country_code" => "US"],
        ["city" => "Melbourne (Avalon)", "country_code" => "AU"],
        ["city" => "Anguilla", "country_code" => "AI"],
        ["city" => "Akita", "country_code" => "JP"],
        ["city" => "Ayers Rock (Uluru)", "country_code" => "AU"],
        ["city" => "Antalya", "country_code" => "TR"],
        ["city" => "Kalamazoo", "country_code" => "US"],
        ["city" => "Samana", "country_code" => "DO"],
        ["city" => "Bahrain", "country_code" => "BH"],
        ["city" => "Baku", "country_code" => "AZ"],
        ["city" => "Baku", "country_code" => "AZ"],
        ["city" => "Barranquilla", "country_code" => "CO"],
        ["city" => "Barnaul", "country_code" => "RU"],
        ["city" => "Balmaceda", "country_code" => "CL"],
        ["city" => "Bhubaneswar", "country_code" => "IN"],
        ["city" => "Barcaldine", "country_code" => "AU"],
        ["city" => "Barcelona", "country_code" => "ES"],
        ["city" => "Bermuda", "country_code" => "BM"],
        ["city" => "Bundaberg", "country_code" => "AU"],
        ["city" => "Vadodara", "country_code" => "IN"],
        ["city" => "Brindisi", "country_code" => "IT"],
        ["city" => "Belgrade", "country_code" => "RS"],
        ["city" => "Benton Harbour", "country_code" => "US"],
        ["city" => "Belem", "country_code" => "BR"],
        ["city" => "Berlin", "country_code" => "DE"],
        ["city" => "Berlin (Tegel)", "country_code" => "DE"],
        ["city" => "Bethel", "country_code" => "US"],
        ["city" => "Bedourie", "country_code" => "AU"],
        ["city" => "Beirut", "country_code" => "LB"],
        ["city" => "Bakersfield", "country_code" => "US"],
        ["city" => "Bloemfontein", "country_code" => "ZA"],
        ["city" => "Belfast (City)", "country_code" => "GB"],
        ["city" => "Belfast (International)", "country_code" => "GB"],
        ["city" => "Bucaramanga", "country_code" => "CO"],
        ["city" => "Barbados", "country_code" => "BB"],
        ["city" => "Binghamton", "country_code" => "US"],
        ["city" => "Bergen", "country_code" => "NO"],
        ["city" => "Bangor", "country_code" => "US"],
        ["city" => "Baghdad", "country_code" => "IQ"],
        ["city" => "Blenheim", "country_code" => "NZ"],
        ["city" => "Bhuj", "country_code" => "IN"],
        ["city" => "Birmingham (US)", "country_code" => "US"],
        ["city" => "Bhopal", "country_code" => "IN"],
        ["city" => "Broken Hill", "country_code" => "AU"],
        ["city" => "Bhavnagar", "country_code" => "IN"],
        ["city" => "Birmingham (UK)", "country_code" => "GB"],
        ["city" => "Belo Horizonte", "country_code" => "BR"],
        ["city" => "Biak", "country_code" => "ID"],
        ["city" => "Billings", "country_code" => "US"],
        ["city" => "Bilbao", "country_code" => "ES"],
        ["city" => "Bismark", "country_code" => "US"],
        ["city" => "Bujumbura", "country_code" => "BI"],
        ["city" => "Beijing", "country_code" => "CN"],
        ["city" => "Beijing", "country_code" => "CN"],
        ["city" => "Leon Guanajuato", "country_code" => "MX"],
        ["city" => "Badajoz", "country_code" => "ES"],
        ["city" => "Kota Kinabalu", "country_code" => "MY"],
        ["city" => "Bangkok", "country_code" => "TH"],
        ["city" => "Blackall", "country_code" => "AU"],
        ["city" => "Bellingham", "country_code" => "US"],
        ["city" => "Billund", "country_code" => "DK"],
        ["city" => "Bologna", "country_code" => "IT"],
        ["city" => "Bangalore", "country_code" => "IN"],
        ["city" => "Blackwater", "country_code" => "AU"],
        ["city" => "Broome", "country_code" => "AU"],
        ["city" => "Bloomington", "country_code" => "US"],
        ["city" => "Banmethuot", "country_code" => "VN"],
        ["city" => "Nashville", "country_code" => "US"],
        ["city" => "Brisbane", "country_code" => "AU"],
        ["city" => "Ballina (Byron)", "country_code" => "AU"],
        ["city" => "Bordeaux", "country_code" => "FR"],
        ["city" => "Bogota", "country_code" => "CO"],
        ["city" => "Boise", "country_code" => "US"],
        ["city" => "Bourgas", "country_code" => "BG"],
        ["city" => "Mumbai", "country_code" => "IN"],
        ["city" => "Boston", "country_code" => "US"],
        ["city" => "Balikpapan", "country_code" => "ID"],
        ["city" => "Porto Seguro", "country_code" => "BR"],
        ["city" => "Beaumont", "country_code" => "US"],
        ["city" => "Boulia", "country_code" => "AU"],
        ["city" => "Blagoveschensk", "country_code" => "RU"],
        ["city" => "San Carlos De Bar", "country_code" => "AR"],
        ["city" => "Bremen", "country_code" => "DE"],
        ["city" => "Bari", "country_code" => "IT"],
        ["city" => "Bourke", "country_code" => "AU"],
        ["city" => "Brownsville", "country_code" => "US"],
        ["city" => "Brussels", "country_code" => "BE"],
        ["city" => "Barrow", "country_code" => "US"],
        ["city" => "Brasilia", "country_code" => "BR"],
        ["city" => "Basel", "country_code" => "CH"],
        ["city" => "Basrah", "country_code" => "IQ"],
        ["city" => "Bratsk", "country_code" => "RU"],
        ["city" => "Baton Rouge", "country_code" => "US"],
        ["city" => "Bintulu", "country_code" => "MY"],
        ["city" => "Burlington", "country_code" => "US"],
        ["city" => "Burketown", "country_code" => "AU"],
        ["city" => "Budapest", "country_code" => "HU"],
        ["city" => "Buenos Aires", "country_code" => "AR"],
        ["city" => "Buenos Aires (Jorge Newbery)", "country_code" => "AR"],
        ["city" => "Buenos Aires (Pistarini)", "country_code" => "AR"],
        ["city" => "Buffalo", "country_code" => "US"],
        ["city" => "Bucharest", "country_code" => "RO"],
        ["city" => "Bucharest", "country_code" => "RO"],
        ["city" => "Bulawayo", "country_code" => "ZW"],
        ["city" => "Burbank", "country_code" => "US"],
        ["city" => "Boa Vista", "country_code" => "BR"],
        ["city" => "Birdsville", "country_code" => "AU"],
        ["city" => "Barrow Island", "country_code" => "AU"],
        ["city" => "Baltimore (Railway)", "country_code" => "US"],
        ["city" => "Washington (Baltimore)", "country_code" => "US"],
        ["city" => "Baltimore", "country_code" => "US"],
        ["city" => "Bandar Seri Begaw", "country_code" => "BN"],
        ["city" => "Burnie", "country_code" => "AU"],
        ["city" => "Belize", "country_code" => "BZ"],
        ["city" => "Briansk", "country_code" => "RU"],
        ["city" => "Bozeman", "country_code" => "US"],
        ["city" => "Columbia", "country_code" => "US"],
        ["city" => "Cagliari", "country_code" => "IT"],
        ["city" => "Cairo", "country_code" => "EG"],
        ["city" => "Akron Canton", "country_code" => "US"],
        ["city" => "Guangzhou", "country_code" => "CN"],
        ["city" => "Casablanca (Mohammed V)", "country_code" => "MA"],
        ["city" => "Casablanca", "country_code" => "MA"],
        ["city" => "Cobar", "country_code" => "AU"],
        ["city" => "Canberra", "country_code" => "AU"],
        ["city" => "Cayo Coco", "country_code" => "CU"],
        ["city" => "Kozhikode", "country_code" => "IN"],
        ["city" => "Cocos Island", "country_code" => "CC"],
        ["city" => "Concepcion", "country_code" => "CL"],
        ["city" => "Caracas", "country_code" => "VE"],
        ["city" => "Kolkata", "country_code" => "IN"],
        ["city" => "Cordova", "country_code" => "US"],
        ["city" => "Cebu", "country_code" => "PH"],
        ["city" => "Chiang Rai", "country_code" => "TH"],
        ["city" => "Chelyabinsk", "country_code" => "RU"],
        ["city" => "Donegal", "country_code" => "IE"],
        ["city" => "Coffs Harbour", "country_code" => "AU"],
        ["city" => "Kerkyra", "country_code" => "GR"],
        ["city" => "Cuiaba", "country_code" => "BR"],
        ["city" => "Cologne", "country_code" => "DE"],
        ["city" => "Cologne (Railway)", "country_code" => "DE"],
        ["city" => "Zhengzhou", "country_code" => "CN"],
        ["city" => "Chittagong", "country_code" => "BD"],
        ["city" => "Changchun", "country_code" => "CN"],
        ["city" => "Campo Grande", "country_code" => "BR"],
        ["city" => "Chattanooga", "country_code" => "US"],
        ["city" => "Christchurch", "country_code" => "NZ"],
        ["city" => "Chicago", "country_code" => "US"],
        ["city" => "Charlottesville", "country_code" => "US"],
        ["city" => "Chania", "country_code" => "GR"],
        ["city" => "Charleston (South Carolina)", "country_code" => "US"],
        ["city" => "Cedar Rapids", "country_code" => "US"],
        ["city" => "Chiclayo", "country_code" => "PE"],
        ["city" => "Coimbatore", "country_code" => "IN"],
        ["city" => "Calama", "country_code" => "CL"],
        ["city" => "Chongqing", "country_code" => "CN"],
        ["city" => "Christmas Creek Mine", "country_code" => "AU"],
        ["city" => "Conakry", "country_code" => "GN"],
        ["city" => "Cleveland (Cuyahoga)", "country_code" => "US"],
        ["city" => "Cleveland (Burke Lakefron)", "country_code" => "US"],
        ["city" => "Cleveland", "country_code" => "US"],
        ["city" => "College Station", "country_code" => "US"],
        ["city" => "Cali", "country_code" => "CO"],
        ["city" => "Colima", "country_code" => "MX"],
        ["city" => "Charlotte", "country_code" => "US"],
        ["city" => "Clearwater", "country_code" => "US"],
        ["city" => "Cunnumulla", "country_code" => "AU"],
        ["city" => "Colombo", "country_code" => "LK"],
        ["city" => "Columbus (Rickenbacker)", "country_code" => "US"],
        ["city" => "Columbus", "country_code" => "US"],
        ["city" => "Champaign", "country_code" => "US"],
        ["city" => "Coonamble", "country_code" => "AU"],
        ["city" => "Cloncurry", "country_code" => "AU"],
        ["city" => "Cairns", "country_code" => "AU"],
        ["city" => "Chiang Mai", "country_code" => "TH"],
        ["city" => "Kochi (Cochin)", "country_code" => "IN"],
        ["city" => "Cordoba", "country_code" => "AR"],
        ["city" => "Colorado Springs", "country_code" => "US"],
        ["city" => "Copenhagen (Roskilde)", "country_code" => "DK"],
        ["city" => "Copenhagen", "country_code" => "DK"],
        ["city" => "Copiapo", "country_code" => "CL"],
        ["city" => "Cape Town", "country_code" => "ZA"],
        ["city" => "Corpus Christi", "country_code" => "US"],
        ["city" => "Charleston (West Virginia)", "country_code" => "US"],
        ["city" => "Columbus", "country_code" => "US"],
        ["city" => "Changsha", "country_code" => "CN"],
        ["city" => "Catania", "country_code" => "IT"],
        ["city" => "Cartagena", "country_code" => "CO"],
        ["city" => "Charleville", "country_code" => "AU"],
        ["city" => "Chengdu", "country_code" => "CN"],
        ["city" => "Cucuta", "country_code" => "CO"],
        ["city" => "Culiacan", "country_code" => "MX"],
        ["city" => "Cancun", "country_code" => "MX"],
        ["city" => "Curacao", "country_code" => "AN"],
        ["city" => "Cuzco", "country_code" => "PE"],
        ["city" => "Cincinnati", "country_code" => "US"],
        ["city" => "Carnarvon", "country_code" => "AU"],
        ["city" => "Curitiba", "country_code" => "BR"],
        ["city" => "Christmas Creek", "country_code" => "AU"],
        ["city" => "Nha Trang (Cam Ranh)", "country_code" => "VN"],
        ["city" => "Cozumel", "country_code" => "MX"],
        ["city" => "Daytona Beach", "country_code" => "US"],
        ["city" => "Dhaka", "country_code" => "BD"],
        ["city" => "Danang", "country_code" => "VN"],
        ["city" => "Damascus", "country_code" => "SY"],
        ["city" => "Danville", "country_code" => "US"],
        ["city" => "Dar Es Salaam", "country_code" => "TZ"],
        ["city" => "Dayton", "country_code" => "US"],
        ["city" => "Dubbo", "country_code" => "AU"],
        ["city" => "Dubuque", "country_code" => "US"],
        ["city" => "Dubrovnik", "country_code" => "HR"],
        ["city" => "Daydream Island", "country_code" => "AU"],
        ["city" => "Delhi", "country_code" => "IN"],
        ["city" => "Denver (Centennial)", "country_code" => "US"],
        ["city" => "Denver", "country_code" => "US"],
        ["city" => "Dallas (Love Field)", "country_code" => "US"],
        ["city" => "Dallas Fort Worth Alliance", "country_code" => "US"],
        ["city" => "Dallas (Addison)", "country_code" => "US"],
        ["city" => "Dallas Fort Worth (Meacham)", "country_code" => "US"],
        ["city" => "Dallas Fort Worth", "country_code" => "US"],
        ["city" => "Mudgee", "country_code" => "AU"],
        ["city" => "Durham Downs", "country_code" => "AU"],
        ["city" => "Dili", "country_code" => "TP"],
        ["city" => "Diu", "country_code" => "IN"],
        ["city" => "Dunk Island", "country_code" => "AU"],
        ["city" => "Dakar", "country_code" => "SN"],
        ["city" => "Dalian", "country_code" => "CN"],
        ["city" => "Dillingham", "country_code" => "US"],
        ["city" => "Duluth", "country_code" => "US"],
        ["city" => "Doomadgee", "country_code" => "AU"],
        ["city" => "Dammam", "country_code" => "SA"],
        ["city" => "Doha", "country_code" => "QA"],
        ["city" => "Donetsk", "country_code" => "UA"],
        ["city" => "Devonport", "country_code" => "AU"],
        ["city" => "Denpasar (Bali)", "country_code" => "ID"],
        ["city" => "Durango", "country_code" => "US"],
        ["city" => "Dresden", "country_code" => "DE"],
        ["city" => "Darwin", "country_code" => "AU"],
        ["city" => "Destin", "country_code" => "US"],
        ["city" => "Des Moines", "country_code" => "US"],
        ["city" => "Dortmund", "country_code" => "DE"],
        ["city" => "Detroit", "country_code" => "US"],
        ["city" => "Dublin", "country_code" => "IE"],
        ["city" => "Dunedin", "country_code" => "NZ"],
        ["city" => "Durban", "country_code" => "ZA"],
        ["city" => "Duesseldorf (Weeze)", "country_code" => "DE"],
        ["city" => "Duesseldorf (Moenchengladbach)", "country_code" => "DE"],
        ["city" => "Dusseldorf", "country_code" => "DE"],
        ["city" => "Davao", "country_code" => "PH"],
        ["city" => "Al Maktoum Intl", "country_code" => "AE"],
        ["city" => "Dubai", "country_code" => "AE"],
        ["city" => "Dushanbe", "country_code" => "TJ"],
        ["city" => "San Sebastian", "country_code" => "ES"],
        ["city" => "Wenatchee", "country_code" => "US"],
        ["city" => "Entebbe", "country_code" => "UG"],
        ["city" => "Erbil", "country_code" => "IQ"],
        ["city" => "Edinburgh", "country_code" => "GB"],
        ["city" => "Edward River", "country_code" => "AU"],
        ["city" => "Vail Eagle", "country_code" => "US"],
        ["city" => "Sege", "country_code" => "SB"],
        ["city" => "Tortola", "country_code" => "VG"],
        ["city" => "Elcho Island", "country_code" => "AU"],
        ["city" => "Elmira", "country_code" => "US"],
        ["city" => "El Paso", "country_code" => "US"],
        ["city" => "Gassim", "country_code" => "SA"],
        ["city" => "East London", "country_code" => "ZA"],
        ["city" => "Emerald", "country_code" => "AU"],
        ["city" => "Esperance", "country_code" => "AU"],
        ["city" => "Erie", "country_code" => "US"],
        ["city" => "El Salvador", "country_code" => "CL"],
        ["city" => "Eugene", "country_code" => "US"],
        ["city" => "Yerevan", "country_code" => "AM"],
        ["city" => "Evansville", "country_code" => "US"],
        ["city" => "New Bern", "country_code" => "US"],
        ["city" => "Exmouth", "country_code" => "AU"],
        ["city" => "El Yopal", "country_code" => "CO"],
        ["city" => "Key West", "country_code" => "US"],
        ["city" => "Fairbanks", "country_code" => "US"],
        ["city" => "Faro", "country_code" => "PT"],
        ["city" => "Fargo", "country_code" => "US"],
        ["city" => "Fresno", "country_code" => "US"],
        ["city" => "Fayetteville (North Carolina)", "country_code" => "US"],
        ["city" => "Kalispell", "country_code" => "US"],
        ["city" => "Fort De France", "country_code" => "MQ"],
        ["city" => "Friedrichshafen", "country_code" => "DE"],
        ["city" => "Fitzroy Crossing", "country_code" => "AU"],
        ["city" => "Karlsruhe", "country_code" => "DE"],
        ["city" => "Fukushima", "country_code" => "JP"],
        ["city" => "Flagstaff", "country_code" => "US"],
        ["city" => "Fort Lauderdale", "country_code" => "US"],
        ["city" => "Florianopolis", "country_code" => "BR"],
        ["city" => "Florence (US)", "country_code" => "US"],
        ["city" => "Florence", "country_code" => "IT"],
        ["city" => "Muenster", "country_code" => "DE"],
        ["city" => "Fort Myers", "country_code" => "US"],
        ["city" => "Fort Myers", "country_code" => "US"],
        ["city" => "Freetown", "country_code" => "SL"],
        ["city" => "Funchal", "country_code" => "PT"],
        ["city" => "Flint", "country_code" => "US"],
        ["city" => "Fuzhou", "country_code" => "CN"],
        ["city" => "Fortaleza", "country_code" => "BR"],
        ["city" => "Freeport", "country_code" => "BS"],
        ["city" => "Frankfurt (Railway)", "country_code" => "DE"],
        ["city" => "Frankfurt", "country_code" => "DE"],
        ["city" => "Bishkek", "country_code" => "KG"],
        ["city" => "Sioux Falls", "country_code" => "US"],
        ["city" => "El Calafate", "country_code" => "AR"],
        ["city" => "Fuerteventura Island", "country_code" => "ES"],
        ["city" => "Fukuoka", "country_code" => "JP"],
        ["city" => "Funafuti", "country_code" => "TV"],
        ["city" => "Fort Wayne", "country_code" => "US"],
        ["city" => "Fayetteville", "country_code" => "US"],
        ["city" => "Fayetteville", "country_code" => "US"],
        ["city" => "Yamagata", "country_code" => "JP"],
        ["city" => "Gan Island", "country_code" => "MV"],
        ["city" => "Gauhati", "country_code" => "IN"],
        ["city" => "Gaya", "country_code" => "IN"],
        ["city" => "Gaborone", "country_code" => "BW"],
        ["city" => "Ginbata", "country_code" => "AU"],
        ["city" => "Garden City", "country_code" => "US"],
        ["city" => "Grand Cayman Island", "country_code" => "KY"],
        ["city" => "Guadalajara", "country_code" => "MX"],
        ["city" => "Gdansk", "country_code" => "PL"],
        ["city" => "Magadan", "country_code" => "RU"],
        ["city" => "Spokane", "country_code" => "US"],
        ["city" => "Spokane", "country_code" => "US"],
        ["city" => "Geraldton", "country_code" => "AU"],
        ["city" => "Griffith", "country_code" => "AU"],
        ["city" => "Grafton", "country_code" => "AU"],
        ["city" => "Longview", "country_code" => "US"],
        ["city" => "Gibraltar", "country_code" => "GI"],
        ["city" => "Gisborne", "country_code" => "NZ"],
        ["city" => "Grand Junction", "country_code" => "US"],
        ["city" => "Glasgow (Prestwick)", "country_code" => "GB"],
        ["city" => "Glasgow", "country_code" => "GB"],
        ["city" => "Gladstone", "country_code" => "AU"],
        ["city" => "Grenada", "country_code" => "GD"],
        ["city" => "Gainesville", "country_code" => "US"],
        ["city" => "Genoa", "country_code" => "IT"],
        ["city" => "Goa", "country_code" => "IN"],
        ["city" => "Nizhniv Novgorod", "country_code" => "RU"],
        ["city" => "Gosford", "country_code" => "AU"],
        ["city" => "Gothenburg", "country_code" => "SE"],
        ["city" => "Gove (Nhulunbuy)", "country_code" => "AU"],
        ["city" => "San Cristobal", "country_code" => "EC"],
        ["city" => "Galapagos Island", "country_code" => "EC"],
        ["city" => "Gulfport", "country_code" => "US"],
        ["city" => "Green Bay", "country_code" => "US"],
        ["city" => "Grand Island", "country_code" => "US"],
        ["city" => "George", "country_code" => "ZA"],
        ["city" => "Grand Rapids", "country_code" => "US"],
        ["city" => "Granada", "country_code" => "ES"],
        ["city" => "Graz", "country_code" => "AT"],
        ["city" => "Greensboro", "country_code" => "US"],
        ["city" => "Greenville (South Carolina)", "country_code" => "US"],
        ["city" => "Gustavus", "country_code" => "US"],
        ["city" => "Groote Eylandt", "country_code" => "AU"],
        ["city" => "Great Falls", "country_code" => "US"],
        ["city" => "Guatemala City", "country_code" => "GT"],
        ["city" => "Gunnison", "country_code" => "US"],
        ["city" => "Guam", "country_code" => "GU"],
        ["city" => "Geneva", "country_code" => "CH"],
        ["city" => "Guayaquil", "country_code" => "EC"],
        ["city" => "Guaymas", "country_code" => "MX"],
        ["city" => "Goiania", "country_code" => "BR"],
        ["city" => "Gizo", "country_code" => "SB"],
        ["city" => "Hanover", "country_code" => "DE"],
        ["city" => "Haikou", "country_code" => "CN"],
        ["city" => "Hamburg", "country_code" => "DE"],
        ["city" => "Hanoi", "country_code" => "VN"],
        ["city" => "Long Island", "country_code" => "AU"],
        ["city" => "Harrisburg", "country_code" => "US"],
        ["city" => "Harrisburg", "country_code" => "US"],
        ["city" => "Hail", "country_code" => "SA"],
        ["city" => "Havana", "country_code" => "CU"],
        ["city" => "Hobart", "country_code" => "AU"],
        ["city" => "Alexandria (Borg El Arab)", "country_code" => "EG"],
        ["city" => "Halls Creek", "country_code" => "AU"],
        ["city" => "Hoedspruit", "country_code" => "ZA"],
        ["city" => "Helsinki", "country_code" => "FI"],
        ["city" => "Heraklion", "country_code" => "GR"],
        ["city" => "Hartford", "country_code" => "US"],
        ["city" => "Hefei", "country_code" => "CN"],
        ["city" => "Hughenden", "country_code" => "AU"],
        ["city" => "Hangzhou", "country_code" => "CN"],
        ["city" => "Mt Hagen", "country_code" => "PG"],
        ["city" => "Hilton Head Island", "country_code" => "US"],
        ["city" => "Horn Island", "country_code" => "AU"],
        ["city" => "Hiroshima", "country_code" => "JP"],
        ["city" => "Honiara", "country_code" => "SB"],
        ["city" => "Hayman Island", "country_code" => "AU"],
        ["city" => "Hivaro", "country_code" => "PG"],
        ["city" => "Khajuraho", "country_code" => "IN"],
        ["city" => "Hakodate", "country_code" => "JP"],
        ["city" => "Hong Kong", "country_code" => "HK"],
        ["city" => "Hokitika", "country_code" => "NZ"],
        ["city" => "Phuket", "country_code" => "TH"],
        ["city" => "Lanseria", "country_code" => "ZA"],
        ["city" => "Helena", "country_code" => "US"],
        ["city" => "Hamilton", "country_code" => "NZ"],
        ["city" => "Hermosillo", "country_code" => "MX"],
        ["city" => "Morioka", "country_code" => "JP"],
        ["city" => "Honolulu (Hickam)", "country_code" => "US"],
        ["city" => "Honolulu (Barbers Point)", "country_code" => "US"],
        ["city" => "Kapolei (Kalaeloa)", "country_code" => "US"],
        ["city" => "Honolulu", "country_code" => "US"],
        ["city" => "Holguin", "country_code" => "CU"],
        ["city" => "Houston (Hobby)", "country_code" => "US"],
        ["city" => "Houston (Bush)", "country_code" => "US"],
        ["city" => "Hai Phong", "country_code" => "VN"],
        ["city" => "Westchster County", "country_code" => "US"],
        ["city" => "Harbin", "country_code" => "CN"],
        ["city" => "Harare", "country_code" => "ZW"],
        ["city" => "Hurghada", "country_code" => "EG"],
        ["city" => "Hambantota", "country_code" => "LK"],
        ["city" => "Kharkov", "country_code" => "UA"],
        ["city" => "Huntsville", "country_code" => "US"],
        ["city" => "Chita", "country_code" => "RU"],
        ["city" => "Hamilton Island", "country_code" => "AU"],
        ["city" => "Huntington", "country_code" => "US"],
        ["city" => "Hue", "country_code" => "VN"],
        ["city" => "Huatulco", "country_code" => "MX"],
        ["city" => "Fraser Coast (Hervey Bay)", "country_code" => "AU"],
        ["city" => "New Haven", "country_code" => "US"],
        ["city" => "Hyderabad", "country_code" => "IN"],
        ["city" => "Yaroslavl", "country_code" => "RU"],
        ["city" => "Ibague", "country_code" => "CO"],
        ["city" => "Ibiza", "country_code" => "ES"],
        ["city" => "Wichita", "country_code" => "US"],
        ["city" => "Indore", "country_code" => "IN"],
        ["city" => "Kiev", "country_code" => "UA"],
        ["city" => "Kiev", "country_code" => "UA"],
        ["city" => "Iguazu", "country_code" => "AR"],
        ["city" => "Iguassu Falls", "country_code" => "BR"],
        ["city" => "Tehran (Imam Khomeini)", "country_code" => "IR"],
        ["city" => "Irkutsk", "country_code" => "RU"],
        ["city" => "Wilmington", "country_code" => "US"],
        ["city" => "Imphal", "country_code" => "IN"],
        ["city" => "Imperatriz", "country_code" => "BR"],
        ["city" => "Indianapolis", "country_code" => "US"],
        ["city" => "Innsbruck", "country_code" => "AT"],
        ["city" => "Inverness", "country_code" => "GB"],
        ["city" => "Isle Of Man", "country_code" => "GB"],
        ["city" => "Ilheus", "country_code" => "BR"],
        ["city" => "Easter Island", "country_code" => "CL"],
        ["city" => "Williamsport", "country_code" => "US"],
        ["city" => "Iquique", "country_code" => "CL"],
        ["city" => "Iquitos", "country_code" => "PE"],
        ["city" => "Mount Isa", "country_code" => "AU"],
        ["city" => "Islamabad", "country_code" => "PK"],
        ["city" => "Ishigaki", "country_code" => "JP"],
        ["city" => "Kinston", "country_code" => "US"],
        ["city" => "Islip", "country_code" => "US"],
        ["city" => "Istanbul", "country_code" => "TR"],
        ["city" => "Sulaymaniyah", "country_code" => "IQ"],
        ["city" => "Ithaca", "country_code" => "US"],
        ["city" => "Hilo", "country_code" => "US"],
        ["city" => "Invercargill", "country_code" => "NZ"],
        ["city" => "Ivalo", "country_code" => "FI"],
        ["city" => "Inverell", "country_code" => "AU"],
        ["city" => "Agartala", "country_code" => "IN"],
        ["city" => "Bagdogra", "country_code" => "IN"],
        ["city" => "Chandigarh", "country_code" => "IN"],
        ["city" => "Mangalore", "country_code" => "IN"],
        ["city" => "Jammu", "country_code" => "IN"],
        ["city" => "Leh", "country_code" => "IN"],
        ["city" => "Madurai", "country_code" => "IN"],
        ["city" => "Aurangabad", "country_code" => "IN"],
        ["city" => "Port Blair", "country_code" => "IN"],
        ["city" => "Izmir", "country_code" => "TR"],
        ["city" => "Izumo", "country_code" => "JP"],
        ["city" => "Jackson Hole", "country_code" => "US"],
        ["city" => "Jaipur", "country_code" => "IN"],
        ["city" => "Jackson", "country_code" => "US"],
        ["city" => "Jacksonville (Craig)", "country_code" => "US"],
        ["city" => "Jacksonville", "country_code" => "US"],
        ["city" => "Julia Creek", "country_code" => "AU"],
        ["city" => "Jodhpur", "country_code" => "IN"],
        ["city" => "Jeddah", "country_code" => "SA"],
        ["city" => "Jersey", "country_code" => "GB"],
        ["city" => "Johor Bahru", "country_code" => "MY"],
        ["city" => "Shute Harbour", "country_code" => "AU"],
        ["city" => "Jakarta", "country_code" => "ID"],
        ["city" => "Mykonos", "country_code" => "GR"],
        ["city" => "Jamestown", "country_code" => "US"],
        ["city" => "Johannesburg (Grand Central)", "country_code" => "ZA"],
        ["city" => "Johannesburg", "country_code" => "ZA"],
        ["city" => "Johannesburg (Railway)", "country_code" => "ZA"],
        ["city" => "Juneau", "country_code" => "US"],
        ["city" => "Joensuu", "country_code" => "FI"],
        ["city" => "Yogyakarta", "country_code" => "ID"],
        ["city" => "Joinville", "country_code" => "BR"],
        ["city" => "Joao Pessoa", "country_code" => "BR"],
        ["city" => "Jorhat", "country_code" => "IN"],
        ["city" => "Kilimanjaro", "country_code" => "TZ"],
        ["city" => "Skiathos", "country_code" => "GR"],
        ["city" => "Thira", "country_code" => "GR"],
        ["city" => "Juba", "country_code" => "SD"],
        ["city" => "Juliaca", "country_code" => "PE"],
        ["city" => "Juizhai Huanglong", "country_code" => "CN"],
        ["city" => "Kajaani", "country_code" => "FI"],
        ["city" => "Kuusamo", "country_code" => "FI"],
        ["city" => "Kaitaia", "country_code" => "NZ"],
        ["city" => "Kabul", "country_code" => "AF"],
        ["city" => "Kota Bharu", "country_code" => "MY"],
        ["city" => "Krabi", "country_code" => "TH"],
        ["city" => "Kuching", "country_code" => "MY"],
        ["city" => "Kochi", "country_code" => "JP"],
        ["city" => "Kemerovo", "country_code" => "RU"],
        ["city" => "Cloudbreak", "country_code" => "AU"],
        ["city" => "Kangaroo Island (Kingscote)", "country_code" => "AU"],
        ["city" => "Kaliningrad", "country_code" => "RU"],
        ["city" => "Kalgoorlie", "country_code" => "AU"],
        ["city" => "Kos", "country_code" => "GR"],
        ["city" => "Kaohsiung", "country_code" => "TW"],
        ["city" => "Karachi", "country_code" => "PK"],
        ["city" => "Nanchang", "country_code" => "CN"],
        ["city" => "Khabarovsk", "country_code" => "RU"],
        ["city" => "Niigata", "country_code" => "JP"],
        ["city" => "Kimberley", "country_code" => "ZA"],
        ["city" => "Kingston", "country_code" => "JM"],
        ["city" => "Kishinev", "country_code" => "MD"],
        ["city" => "Krasnojarsk", "country_code" => "RU"],
        ["city" => "Kerikeri (Bays of Islands)", "country_code" => "NZ"],
        ["city" => "Kita Kyushu", "country_code" => "JP"],
        ["city" => "Kaluga", "country_code" => "RU"],
        ["city" => "Kalibo", "country_code" => "PH"],
        ["city" => "Kalamata", "country_code" => "GR"],
        ["city" => "Kunming", "country_code" => "CN"],
        ["city" => "Miyazaki", "country_code" => "JP"],
        ["city" => "Kumamoto", "country_code" => "JP"],
        ["city" => "Komatsu", "country_code" => "JP"],
        ["city" => "Kuala Namu", "country_code" => "ID"],
        ["city" => "Kununurra", "country_code" => "AU"],
        ["city" => "Kona", "country_code" => "US"],
        ["city" => "Kagoshima", "country_code" => "JP"],
        ["city" => "Kempsey", "country_code" => "AU"],
        ["city" => "Krakow", "country_code" => "PL"],
        ["city" => "Krasnodar", "country_code" => "RU"],
        ["city" => "Khartoum", "country_code" => "SD"],
        ["city" => "Karratha", "country_code" => "AU"],
        ["city" => "Kathmandu", "country_code" => "NP"],
        ["city" => "Ketchikan", "country_code" => "US"],
        ["city" => "Katherine", "country_code" => "AU"],
        ["city" => "Kuantan", "country_code" => "MY"],
        ["city" => "Samara", "country_code" => "RU"],
        ["city" => "Kushiro", "country_code" => "JP"],
        ["city" => "Kuala Lumpur (Subang)", "country_code" => "MY"],
        ["city" => "Kuala Lumpur", "country_code" => "MY"],
        ["city" => "Yakushima", "country_code" => "JP"],
        ["city" => "Kuopio", "country_code" => "FI"],
        ["city" => "Kavala", "country_code" => "GR"],
        ["city" => "Kuwait", "country_code" => "KW"],
        ["city" => "Guilin", "country_code" => "CN"],
        ["city" => "Kowanyama", "country_code" => "AU"],
        ["city" => "Kazan", "country_code" => "RU"],
        ["city" => "Luanda", "country_code" => "AO"],
        ["city" => "Las Vegas (Henderson Sky Harbor)", "country_code" => "US"],
        ["city" => "Las Vegas (North)", "country_code" => "US"],
        ["city" => "Las Vegas", "country_code" => "US"],
        ["city" => "Santa Monica", "country_code" => "US"],
        ["city" => "Los Angeles (City)", "country_code" => "US"],
        ["city" => "Los Angeles (Commerce Bus Park)", "country_code" => "US"],
        ["city" => "Los Angeles", "country_code" => "US"],
        ["city" => "Los Angeles", "country_code" => "US"],
        ["city" => "Leeds", "country_code" => "GB"],
        ["city" => "Lubbock", "country_code" => "US"],
        ["city" => "Khudzhand", "country_code" => "TJ"],
        ["city" => "Labasa", "country_code" => "FJ"],
        ["city" => "Labuan", "country_code" => "MY"],
        ["city" => "Larnaca", "country_code" => "CY"],
        ["city" => "La Coruna", "country_code" => "ES"],
        ["city" => "Lake Charles", "country_code" => "US"],
        ["city" => "Londrina", "country_code" => "BR"],
        ["city" => "Lord Howe Island", "country_code" => "AU"],
        ["city" => "Exmouth (Learmonth)", "country_code" => "AU"],
        ["city" => "St Petersburg", "country_code" => "RU"],
        ["city" => "Almeria", "country_code" => "ES"],
        ["city" => "Leipzig", "country_code" => "DE"],
        ["city" => "Leon", "country_code" => "ES"],
        ["city" => "Leinster", "country_code" => "AU"],
        ["city" => "Lexington", "country_code" => "US"],
        ["city" => "Lafayette", "country_code" => "US"],
        ["city" => "Long Beach", "country_code" => "US"],
        ["city" => "Leigh Creek", "country_code" => "AU"],
        ["city" => "Langkawi", "country_code" => "MY"],
        ["city" => "Lahore", "country_code" => "PK"],
        ["city" => "Lightning Ridge", "country_code" => "AU"],
        ["city" => "Lanzhou", "country_code" => "CN"],
        ["city" => "Kauai Island (Lihue)", "country_code" => "US"],
        ["city" => "Lima", "country_code" => "PE"],
        ["city" => "Liberia", "country_code" => "CR"],
        ["city" => "Lisbon", "country_code" => "PT"],
        ["city" => "Little Rock", "country_code" => "US"],
        ["city" => "Ljubljana", "country_code" => "SI"],
        ["city" => "Lucknow", "country_code" => "IN"],
        ["city" => "Malelane", "country_code" => "ZA"],
        ["city" => "Lanai", "country_code" => "US"],
        ["city" => "Linz", "country_code" => "AT"],
        ["city" => "London (Stansted)", "country_code" => "GB"],
        ["city" => "London (Southend)", "country_code" => "GB"],
        ["city" => "London (City)", "country_code" => "GB"],
        ["city" => "London (Luton)", "country_code" => "GB"],
        ["city" => "London (Heathrow)", "country_code" => "GB"],
        ["city" => "London (Gatwick)", "country_code" => "GB"],
        ["city" => "London", "country_code" => "GB"],
        ["city" => "Lombok", "country_code" => "ID"],
        ["city" => "Lagos", "country_code" => "NG"],
        ["city" => "Gran Canaria", "country_code" => "ES"],
        ["city" => "La Paz", "country_code" => "BO"],
        ["city" => "Lipetsk", "country_code" => "RU"],
        ["city" => "Lampang", "country_code" => "TH"],
        ["city" => "Laredo", "country_code" => "US"],
        ["city" => "Longreach", "country_code" => "AU"],
        ["city" => "Casa De Campo", "country_code" => "DO"],
        ["city" => "La Serena", "country_code" => "CL"],
        ["city" => "La Crosse", "country_code" => "US"],
        ["city" => "Launceston", "country_code" => "AU"],
        ["city" => "Lismore", "country_code" => "AU"],
        ["city" => "Tzaneen", "country_code" => "ZA"],
        ["city" => "Loreto", "country_code" => "MX"],
        ["city" => "Lusaka", "country_code" => "ZM"],
        ["city" => "Luxembourg", "country_code" => "LU"],
        ["city" => "Livingstone", "country_code" => "ZM"],
        ["city" => "Laverton", "country_code" => "AU"],
        ["city" => "Leninakan", "country_code" => "AM"],
        ["city" => "Lewiston", "country_code" => "US"],
        ["city" => "Luxor", "country_code" => "EG"],
        ["city" => "Lynchburg", "country_code" => "US"],
        ["city" => "Lyon (Bron)", "country_code" => "FR"],
        ["city" => "Lyon", "country_code" => "FR"],
        ["city" => "Lizard Island", "country_code" => "AU"],
        ["city" => "Chennai", "country_code" => "IN"],
        ["city" => "Maraba", "country_code" => "BR"],
        ["city" => "Madrid (Torrejon)", "country_code" => "ES"],
        ["city" => "Madrid", "country_code" => "ES"],
        ["city" => "Midland Odessa", "country_code" => "US"],
        ["city" => "Menorca", "country_code" => "ES"],
        ["city" => "Manchester", "country_code" => "GB"],
        ["city" => "Manchester (Railway)", "country_code" => "GB"],
        ["city" => "Manaus", "country_code" => "BR"],
        ["city" => "Mmabatho", "country_code" => "ZA"],
        ["city" => "Maryborough", "country_code" => "AU"],
        ["city" => "Montego Bay", "country_code" => "JM"],
        ["city" => "Macapa", "country_code" => "BR"],
        ["city" => "Muscat", "country_code" => "OM"],
        ["city" => "McArthur River", "country_code" => "AU"],
        ["city" => "Sunshine Coast (Maroochydore)", "country_code" => "AU"],
        ["city" => "Maceio", "country_code" => "BR"],
        ["city" => "Medellin (J M Cordova)", "country_code" => "CO"],
        ["city" => "Medellin (Olaya Herrera)", "country_code" => "CO"],
        ["city" => "Mendi", "country_code" => "PG"],
        ["city" => "Mendoza", "country_code" => "AR"],
        ["city" => "Madinah", "country_code" => "SA"],
        ["city" => "Melbourne (Essendon)", "country_code" => "AU"],
        ["city" => "Melbourne (Yarra Bank)", "country_code" => "AU"],
        ["city" => "Melbourne", "country_code" => "AU"],
        ["city" => "Memphis", "country_code" => "US"],
        ["city" => "Medan", "country_code" => "ID"],
        ["city" => "Mexico City (Toluca)", "country_code" => "MX"],
        ["city" => "Mexico City", "country_code" => "MX"],
        ["city" => "Mcallen", "country_code" => "US"],
        ["city" => "Macau", "country_code" => "MO"],
        ["city" => "Medford", "country_code" => "US"],
        ["city" => "Mt Gambier", "country_code" => "AU"],
        ["city" => "Margate", "country_code" => "ZA"],
        ["city" => "Montgomery", "country_code" => "US"],
        ["city" => "Milingimbi", "country_code" => "AU"],
        ["city" => "Mocopulli", "country_code" => "CL"],
        ["city" => "Mashad", "country_code" => "IR"],
        ["city" => "Manhattan", "country_code" => "US"],
        ["city" => "Manchester (US)", "country_code" => "US"],
        ["city" => "Mount Hotham", "country_code" => "AU"],
        ["city" => "Miami (Opa Locka)", "country_code" => "US"],
        ["city" => "Miami (Seaplane Base)", "country_code" => "US"],
        ["city" => "Miami (Downtown)", "country_code" => "US"],
        ["city" => "Miami", "country_code" => "US"],
        ["city" => "Merida", "country_code" => "MX"],
        ["city" => "Milan (Malpensa)", "country_code" => "IT"],
        ["city" => "Milan", "country_code" => "IT"],
        ["city" => "Milan (Linate)", "country_code" => "IT"],
        ["city" => "Merimbula", "country_code" => "AU"],
        ["city" => "Monkey Mia", "country_code" => "AU"],
        ["city" => "Mytilene", "country_code" => "GR"],
        ["city" => "Murcia", "country_code" => "ES"],
        ["city" => "Mirnyj", "country_code" => "RU"],
        ["city" => "Kansas City", "country_code" => "US"],
        ["city" => "Kansas City", "country_code" => "US"],
        ["city" => "Milwaukee", "country_code" => "US"],
        ["city" => "Milwaukee", "country_code" => "US"],
        ["city" => "Muskegon", "country_code" => "US"],
        ["city" => "Hoolehua", "country_code" => "US"],
        ["city" => "Meekatharra", "country_code" => "AU"],
        ["city" => "Mackay", "country_code" => "AU"],
        ["city" => "Malta", "country_code" => "MT"],
        ["city" => "Melbourne (US)", "country_code" => "US"],
        ["city" => "Male", "country_code" => "MV"],
        ["city" => "Moline", "country_code" => "US"],
        ["city" => "Melilla", "country_code" => "ES"],
        ["city" => "Monroe", "country_code" => "US"],
        ["city" => "Memanbetsu", "country_code" => "JP"],
        ["city" => "Mammoth Lakes", "country_code" => "US"],
        ["city" => "Matsumoto", "country_code" => "JP"],
        ["city" => "Middlemount", "country_code" => "AU"],
        ["city" => "Miyako", "country_code" => "JP"],
        ["city" => "Maningrida", "country_code" => "AU"],
        ["city" => "Manila", "country_code" => "PH"],
        ["city" => "Mobile", "country_code" => "US"],
        ["city" => "Moranbah", "country_code" => "AU"],
        ["city" => "Moscow", "country_code" => "RU"],
        ["city" => "Moscow (Sheremetyevo)", "country_code" => "RU"],
        ["city" => "Moscow (Domodedovo)", "country_code" => "RU"],
        ["city" => "Montpellier", "country_code" => "FR"],
        ["city" => "Maputo", "country_code" => "MZ"],
        ["city" => "Mount Pleasant", "country_code" => "FK"],
        ["city" => "Mildura", "country_code" => "AU"],
        ["city" => "Sawyer Intnl", "country_code" => "US"],
        ["city" => "Marco Island", "country_code" => "US"],
        ["city" => "Marseille", "country_code" => "FR"],
        ["city" => "Mauritius", "country_code" => "MU"],
        ["city" => "Mineralnye", "country_code" => "RU"],
        ["city" => "Monterey (US)", "country_code" => "US"],
        ["city" => "Moree", "country_code" => "AU"],
        ["city" => "Misawa", "country_code" => "JP"],
        ["city" => "Madison", "country_code" => "US"],
        ["city" => "Missoula", "country_code" => "US"],
        ["city" => "Minneapolis (Flying Cloud)", "country_code" => "US"],
        ["city" => "Minneapolis (Crystal)", "country_code" => "US"],
        ["city" => "Minneapolis (Downtown)", "country_code" => "US"],
        ["city" => "Minneapolis", "country_code" => "US"],
        ["city" => "New Orleans", "country_code" => "US"],
        ["city" => "Montrose", "country_code" => "US"],
        ["city" => "Monteria", "country_code" => "CO"],
        ["city" => "Minatitlan", "country_code" => "MX"],
        ["city" => "Monterrey (Mexico)", "country_code" => "MX"],
        ["city" => "Munda", "country_code" => "SB"],
        ["city" => "Munich", "country_code" => "DE"],
        ["city" => "Munich", "country_code" => "DE"],
        ["city" => "Munich (Railway)", "country_code" => "DE"],
        ["city" => "Montevideo", "country_code" => "UY"],
        ["city" => "Marthas Vineyard", "country_code" => "US"],
        ["city" => "Moruya", "country_code" => "AU"],
        ["city" => "Matsuyama", "country_code" => "JP"],
        ["city" => "Myrtle Beach", "country_code" => "US"],
        ["city" => "Miri", "country_code" => "MY"],
        ["city" => "Mazatlan", "country_code" => "MX"],
        ["city" => "Narrabri", "country_code" => "AU"],
        ["city" => "Nagpur", "country_code" => "IN"],
        ["city" => "Nadi", "country_code" => "FJ"],
        ["city" => "Naples (Railway)", "country_code" => "IT"],
        ["city" => "Naples", "country_code" => "IT"],
        ["city" => "Nassau", "country_code" => "BS"],
        ["city" => "Natal", "country_code" => "BR"],
        ["city" => "Naberevnye Chelny", "country_code" => "RU"],
        ["city" => "Nairobi", "country_code" => "KE"],
        ["city" => "Nice", "country_code" => "FR"],
        ["city" => "Newcastle (UK)", "country_code" => "GB"],
        ["city" => "Clark International Airport", "country_code" => "PH"],
        ["city" => "Ningbo", "country_code" => "CN"],
        ["city" => "Nagoya", "country_code" => "JP"],
        ["city" => "Nagasaki", "country_code" => "JP"],
        ["city" => "Nha Trang (Cam Ranh)", "country_code" => "VN"],
        ["city" => "Nizhnevartovsk", "country_code" => "RU"],
        ["city" => "Al Najaf Iraq", "country_code" => "IQ"],
        ["city" => "Nanjing", "country_code" => "CN"],
        ["city" => "Norfolk Island", "country_code" => "NF"],
        ["city" => "Kruger Mpumalanga", "country_code" => "ZA"],
        ["city" => "Nelspruit", "country_code" => "ZA"],
        ["city" => "Nanning", "country_code" => "CN"],
        ["city" => "Noumea (Magenta)", "country_code" => "NC"],
        ["city" => "Noumea", "country_code" => "NC"],
        ["city" => "Novokuznetsk", "country_code" => "RU"],
        ["city" => "Napier", "country_code" => "NZ"],
        ["city" => "New Plymouth", "country_code" => "NZ"],
        ["city" => "Norilsk", "country_code" => "RU"],
        ["city" => "Nelson", "country_code" => "NZ"],
        ["city" => "Belmont", "country_code" => "AU"],
        ["city" => "Newcastle (Port Stephens)", "country_code" => "AU"],
        ["city" => "Newcastle", "country_code" => "AU"],
        ["city" => "Normanton", "country_code" => "AU"],
        ["city" => "Sun City", "country_code" => "ZA"],
        ["city" => "Nuremburg", "country_code" => "DE"],
        ["city" => "Nuremburg (Railway)", "country_code" => "DE"],
        ["city" => "Novyj Urengoj", "country_code" => "RU"],
        ["city" => "Neiva", "country_code" => "CO"],
        ["city" => "Navegantes", "country_code" => "BR"],
        ["city" => "New York", "country_code" => "US"],
        ["city" => "New York (JFK)", "country_code" => "US"],
        ["city" => "New York (Newark)", "country_code" => "US"],
        ["city" => "Plattsburgh Intl (New York)", "country_code" => "US"],
        ["city" => "New York (La Guardia)", "country_code" => "US"],
        ["city" => "Nadym", "country_code" => "RU"],
        ["city" => "Orange", "country_code" => "AU"],
        ["city" => "Jacksonville (North Carolina)", "country_code" => "US"],
        ["city" => "Oakland", "country_code" => "US"],
        ["city" => "Oamaru", "country_code" => "NZ"],
        ["city" => "Obihiro", "country_code" => "JP"],
        ["city" => "Odessa", "country_code" => "UA"],
        ["city" => "Kaanapali", "country_code" => "US"],
        ["city" => "Kahului (Maui)", "country_code" => "US"],
        ["city" => "Vladikavkaz", "country_code" => "RU"],
        ["city" => "Oshima", "country_code" => "JP"],
        ["city" => "Oita", "country_code" => "JP"],
        ["city" => "Okinawa", "country_code" => "JP"],
        ["city" => "Oklahoma City", "country_code" => "US"],
        ["city" => "Okino Erabu", "country_code" => "JP"],
        ["city" => "Oki", "country_code" => "JP"],
        ["city" => "Okayama", "country_code" => "JP"],
        ["city" => "Oakey", "country_code" => "AU"],
        ["city" => "Olbia", "country_code" => "IT"],
        ["city" => "Olympic Dam", "country_code" => "AU"],
        ["city" => "Omaha", "country_code" => "US"],
        ["city" => "Nome", "country_code" => "US"],
        ["city" => "Omsk", "country_code" => "RU"],
        ["city" => "Mornington Island", "country_code" => "AU"],
        ["city" => "Ontario", "country_code" => "US"],
        ["city" => "Gold Coast (Coolangatta)", "country_code" => "AU"],
        ["city" => "Gold Coast", "country_code" => "AU"],
        ["city" => "Cooma", "country_code" => "AU"],
        ["city" => "Porto", "country_code" => "PT"],
        ["city" => "Norfolk (VA)", "country_code" => "US"],
        ["city" => "Norfolk (VA)", "country_code" => "IE"],
        ["city" => "Cork", "country_code" => "IE"],
        ["city" => "Orlando", "country_code" => "US"],
        ["city" => "Orlando", "country_code" => "US"],
        ["city" => "Osaka (Kansai)", "country_code" => "JP"],
        ["city" => "Osaka (Itami)", "country_code" => "JP"],
        ["city" => "Osaka", "country_code" => "JP"],
        ["city" => "Oslo (Sandefjord)", "country_code" => "NO"],
        ["city" => "Oslo", "country_code" => "NO"],
        ["city" => "Oslo", "country_code" => "NO"],
        ["city" => "Oslo", "country_code" => "NO"],
        ["city" => "Osh", "country_code" => "KG"],
        ["city" => "Kotzebue", "country_code" => "US"],
        ["city" => "Oulu", "country_code" => "FI"],
        ["city" => "Novosibirsk", "country_code" => "RU"],
        ["city" => "Asturias", "country_code" => "ES"],
        ["city" => "Paderborn", "country_code" => "DE"],
        ["city" => "Paris (Charles de Gaulle)", "country_code" => "FR"],
        ["city" => "Paris", "country_code" => "FR"],
        ["city" => "Paris (Orly)", "country_code" => "FR"],
        ["city" => "Patna", "country_code" => "IN"],
        ["city" => "Porbandar", "country_code" => "IN"],
        ["city" => "West Palm Beach", "country_code" => "US"],
        ["city" => "Paama", "country_code" => "VU"],
        ["city" => "Paraburdoo", "country_code" => "AU"],
        ["city" => "Plettenberg", "country_code" => "ZA"],
        ["city" => "Pucallpa", "country_code" => "PE"],
        ["city" => "Picton", "country_code" => "NZ"],
        ["city" => "Pedro Bay", "country_code" => "US"],
        ["city" => "Padang", "country_code" => "ID"],
        ["city" => "Portland (Oregon)", "country_code" => "US"],
        ["city" => "Perm", "country_code" => "RU"],
        ["city" => "Pereira", "country_code" => "CO"],
        ["city" => "Puerto Maldonado", "country_code" => "PE"],
        ["city" => "Penang", "country_code" => "MY"],
        ["city" => "Perth", "country_code" => "AU"],
        ["city" => "Perth", "country_code" => "AU"],
        ["city" => "Petrozavodsk", "country_code" => "RU"],
        ["city" => "Peshawar", "country_code" => "PK"],
        ["city" => "Penza", "country_code" => "RU"],
        ["city" => "Greenville (North Carolina)", "country_code" => "US"],
        ["city" => "Port Hedland", "country_code" => "AU"],
        ["city" => "Newport News", "country_code" => "US"],
        ["city" => "Philadelphia (Northeast)", "country_code" => "US"],
        ["city" => "Philadelphia", "country_code" => "US"],
        ["city" => "Phalaborwa", "country_code" => "ZA"],
        ["city" => "Phoenix (Deer Valley)", "country_code" => "US"],
        ["city" => "Phoenix", "country_code" => "US"],
        ["city" => "Peoria", "country_code" => "US"],
        ["city" => "Pittsburgh", "country_code" => "US"],
        ["city" => "Piura", "country_code" => "PE"],
        ["city" => "Petropavlovsk-Kamchats", "country_code" => "RU"],
        ["city" => "Parkes", "country_code" => "AU"],
        ["city" => "Port Lincoln", "country_code" => "AU"],
        ["city" => "Providenciales", "country_code" => "TC"],
        ["city" => "Semipalatinsk", "country_code" => "KZ"],
        ["city" => "Port Elizabeth", "country_code" => "ZA"],
        ["city" => "Puerto Montt", "country_code" => "CL"],
        ["city" => "Palma Mallorca", "country_code" => "ES"],
        ["city" => "Palermo", "country_code" => "IT"],
        ["city" => "Palmerston North", "country_code" => "NZ"],
        ["city" => "Palmas", "country_code" => "BR"],
        ["city" => "Pamplona", "country_code" => "ES"],
        ["city" => "Phnom Penh", "country_code" => "KH"],
        ["city" => "Pune", "country_code" => "IN"],
        ["city" => "Pensacola", "country_code" => "US"],
        ["city" => "Porto Alegre", "country_code" => "BR"],
        ["city" => "Port Moresby", "country_code" => "PG"],
        ["city" => "Puerto Plata", "country_code" => "DO"],
        ["city" => "Port Of Spain", "country_code" => "TT"],
        ["city" => "Poznan", "country_code" => "PL"],
        ["city" => "Proserpine", "country_code" => "AU"],
        ["city" => "Puerto Princesa", "country_code" => "PH"],
        ["city" => "Papeete", "country_code" => "PF"],
        ["city" => "Phu Quoc", "country_code" => "VN"],
        ["city" => "Port Macquarie", "country_code" => "AU"],
        ["city" => "Prague", "country_code" => "CZ"],
        ["city" => "Pristina", "country_code" => "YU"],
        ["city" => "Pisa", "country_code" => "IT"],
        ["city" => "Pasco", "country_code" => "US"],
        ["city" => "Petersburg", "country_code" => "US"],
        ["city" => "Palm Springs", "country_code" => "US"],
        ["city" => "Polokwane", "country_code" => "ZA"],
        ["city" => "Pittsburgh (Municipal)", "country_code" => "US"],
        ["city" => "Panama City", "country_code" => "PA"],
        ["city" => "Port Augusta", "country_code" => "AU"],
        ["city" => "Punta Cana", "country_code" => "DO"],
        ["city" => "Punta Arenas", "country_code" => "CL"],
        ["city" => "Busan", "country_code" => "KR"],
        ["city" => "Puerto Asis", "country_code" => "CO"],
        ["city" => "Pullman", "country_code" => "US"],
        ["city" => "Providence", "country_code" => "US"],
        ["city" => "Porto Velho", "country_code" => "BR"],
        ["city" => "Puerto Vallarta", "country_code" => "MX"],
        ["city" => "Portland", "country_code" => "US"],
        ["city" => "Pavlodar", "country_code" => "KZ"],
        ["city" => "Pietermaritzburg", "country_code" => "ZA"],
        ["city" => "Port Sudan", "country_code" => "SD"],
        ["city" => "Dusseldorf (Railway)", "country_code" => "DE"],
        ["city" => "Queretaro", "country_code" => "MX"],
        ["city" => "Railway Germany", "country_code" => "DE"],
        ["city" => "Rajkot", "country_code" => "IN"],
        ["city" => "Marrakech", "country_code" => "MA"],
        ["city" => "Ribeirao Preto", "country_code" => "BR"],
        ["city" => "Rapid City", "country_code" => "US"],
        ["city" => "Rarotonga", "country_code" => "CK"],
        ["city" => "Rio Branco", "country_code" => "BR"],
        ["city" => "Richards Bay", "country_code" => "ZA"],
        ["city" => "Richmond", "country_code" => "AU"],
        ["city" => "Redding", "country_code" => "US"],
        ["city" => "Redmond", "country_code" => "US"],
        ["city" => "Raleigh Durham", "country_code" => "US"],
        ["city" => "Recife", "country_code" => "BR"],
        ["city" => "Reggio Calabria", "country_code" => "IT"],
        ["city" => "Reykjavik", "country_code" => "IS"],
        ["city" => "Reykjavik", "country_code" => "IS"],
        ["city" => "Siem Reap", "country_code" => "KH"],
        ["city" => "Gorno Altaysk", "country_code" => "RU"],
        ["city" => "Rio Gallegos", "country_code" => "AR"],
        ["city" => "Yangon", "country_code" => "MM"],
        ["city" => "Rhodes Maritsa", "country_code" => "GR"],
        ["city" => "Richmond", "country_code" => "US"],
        ["city" => "Rio De Janeiro (Galeao A C Jobim Intl)", "country_code" => "BR"],
        ["city" => "Rio De Janeiro", "country_code" => "BR"],
        ["city" => "Rio De Janeiro (Santos Dumont)", "country_code" => "BR"],
        ["city" => "Riga", "country_code" => "LV"],
        ["city" => "Logrono", "country_code" => "ES"],
        ["city" => "Roma", "country_code" => "AU"],
        ["city" => "Rimini", "country_code" => "IT"],
        ["city" => "Taichung", "country_code" => "TW"],
        ["city" => "Reno", "country_code" => "US"],
        ["city" => "Roanoke", "country_code" => "US"],
        ["city" => "Rochester (NY)", "country_code" => "US"],
        ["city" => "Rockhampton", "country_code" => "AU"],
        ["city" => "Rome", "country_code" => "IT"],
        ["city" => "Rotorua", "country_code" => "NZ"],
        ["city" => "Rostov", "country_code" => "RU"],
        ["city" => "Raipur", "country_code" => "IN"],
        ["city" => "Rochester", "country_code" => "US"],
        ["city" => "Rotterdam (Railway)", "country_code" => "NL"],
        ["city" => "Rotterdam", "country_code" => "NL"],
        ["city" => "Riyadh", "country_code" => "SA"],
        ["city" => "Marau", "country_code" => "SB"],
        ["city" => "Rovaneimi", "country_code" => "FI"],
        ["city" => "SACRAMENTO (EXECUTIVE)", "country_code" => "US"],
        ["city" => "Sacramento", "country_code" => "US"],
        ["city" => "Santa Fe", "country_code" => "US"],
        ["city" => "Sanaa", "country_code" => "YE"],
        ["city" => "San Salvador", "country_code" => "SV"],
        ["city" => "San Diego (Brown Field)", "country_code" => "US"],
        ["city" => "San Diego (Montgomery)", "country_code" => "US"],
        ["city" => "San Diego", "country_code" => "US"],
        ["city" => "Sao Paulo", "country_code" => "BR"],
        ["city" => "Sao Paulo (Viracopos)", "country_code" => "BR"],
        ["city" => "Sao Paulo (Guarulhos Intl)", "country_code" => "BR"],
        ["city" => "Sao Paulo (Congonhas)", "country_code" => "BR"],
        ["city" => "San Antonio", "country_code" => "US"],
        ["city" => "Savannah", "country_code" => "US"],
        ["city" => "Istanbul (Sabiha Gokcen)", "country_code" => "TR"],
        ["city" => "Santa Barbara", "country_code" => "US"],
        ["city" => "South Bend", "country_code" => "US"],
        ["city" => "San Luis Obispo", "country_code" => "US"],
        ["city" => "Steamboat Springs", "country_code" => "US"],
        ["city" => "Sabah", "country_code" => "PG"],
        ["city" => "Sibu", "country_code" => "MY"],
        ["city" => "Salisbury Ocean", "country_code" => "US"],
        ["city" => "Prudhoe Bay (Deadhorse)", "country_code" => "US"],
        ["city" => "State College", "country_code" => "US"],
        ["city" => "Santiago", "country_code" => "CL"],
        ["city" => "Saarbruecken", "country_code" => "DE"],
        ["city" => "Santiago De Compo (Spain)", "country_code" => "ES"],
        ["city" => "Louisville", "country_code" => "US"],
        ["city" => "Sendai", "country_code" => "JP"],
        ["city" => "Sandakan", "country_code" => "MY"],
        ["city" => "Santo Domingo", "country_code" => "DO"],
        ["city" => "Santander", "country_code" => "ES"],
        ["city" => "Seattle (Boeing Fld King)", "country_code" => "US"],
        ["city" => "Everett", "country_code" => "US"],
        ["city" => "Tacoma", "country_code" => "US"],
        ["city" => "Seattle (Lake Union)", "country_code" => "US"],
        ["city" => "Seattle", "country_code" => "US"],
        ["city" => "Seoul (Incheon)", "country_code" => "KR"],
        ["city" => "Seoul (Gimpo)", "country_code" => "KR"],
        ["city" => "Seoul", "country_code" => "KR"],
        ["city" => "Seychelles", "country_code" => "SC"],
        ["city" => "San Francisco", "country_code" => "US"],
        ["city" => "San Francisco", "country_code" => "US"],
        ["city" => "Surgut", "country_code" => "RU"],
        ["city" => "Springfield Brandson", "country_code" => "US"],
        ["city" => "Ho Chi Minh City", "country_code" => "VN"],
        ["city" => "St George", "country_code" => "AU"],
        ["city" => "Shanghai (Pudong)", "country_code" => "CN"],
        ["city" => "Shanghai (Hongqiao)", "country_code" => "CN"],
        ["city" => "Shenyang", "country_code" => "CN"],
        ["city" => "Sharjah", "country_code" => "AE"],
        ["city" => "Shirahama", "country_code" => "JP"],
        ["city" => "Sanderson Field", "country_code" => "US"],
        ["city" => "Shreveport", "country_code" => "US"],
        ["city" => "Xi An (Xianyang)", "country_code" => "CN"],
        ["city" => "Xi An", "country_code" => "CN"],
        ["city" => "Singapore (Paya Lebar)", "country_code" => "SG"],
        ["city" => "Singapore (Seletar)", "country_code" => "SG"],
        ["city" => "Singapore", "country_code" => "SG"],
        ["city" => "Simferpol", "country_code" => "UA"],
        ["city" => "Sitka", "country_code" => "US"],
        ["city" => "San Jose (CA)", "country_code" => "US"],
        ["city" => "San Jose Del Cabo", "country_code" => "MX"],
        ["city" => "San Jose", "country_code" => "PH"],
        ["city" => "Sarajevo", "country_code" => "BA"],
        ["city" => "San Jose", "country_code" => "CR"],
        ["city" => "Sao Jose Do Rio Preto", "country_code" => "BR"],
        ["city" => "San Juan", "country_code" => "PR"],
        ["city" => "St Kitts", "country_code" => "KN"],
        ["city" => "Thessaloniki", "country_code" => "GR"],
        ["city" => "Skopje", "country_code" => "MK"],
        ["city" => "Salta", "country_code" => "AR"],
        ["city" => "Salt Lake City", "country_code" => "US"],
        ["city" => "Solomon", "country_code" => "AU"],
        ["city" => "Salalah", "country_code" => "OM"],
        ["city" => "Salamanca", "country_code" => "ES"],
        ["city" => "St Lucia", "country_code" => "LC"],
        ["city" => "Sao Luiz", "country_code" => "BR"],
        ["city" => "Samos", "country_code" => "GR"],
        ["city" => "Santa Marta", "country_code" => "CO"],
        ["city" => "Santa Ana", "country_code" => "US"],
        ["city" => "Shannon", "country_code" => "IE"],
        ["city" => "Santa Clara", "country_code" => "CU"],
        ["city" => "Sofia", "country_code" => "BG"],
        ["city" => "South Molle Island", "country_code" => "AU"],
        ["city" => "Solomon (US)", "country_code" => "US"],
        ["city" => "Espiritu Santo", "country_code" => "VU"],
        ["city" => "Santacruz Lapalma", "country_code" => "ES"],
        ["city" => "Springfield", "country_code" => "US"],
        ["city" => "Sapporo (Chitose)", "country_code" => "JP"],
        ["city" => "Sapporo", "country_code" => "JP"],
        ["city" => "Sapporo (Okadama)", "country_code" => "JP"],
        ["city" => "Split", "country_code" => "HR"],
        ["city" => "Semarang", "country_code" => "ID"],
        ["city" => "Sarasota", "country_code" => "US"],
        ["city" => "Santa Cruz (Viru Viru)", "country_code" => "BO"],
        ["city" => "Salvador", "country_code" => "BR"],
        ["city" => "Sharm El Sheikh", "country_code" => "EG"],
        ["city" => "St Louis (Spirit of St Louis)", "country_code" => "US"],
        ["city" => "St Louis", "country_code" => "US"],
        ["city" => "Santarem", "country_code" => "BR"],
        ["city" => "Stockholm", "country_code" => "SE"],
        ["city" => "Stuttgart (Railway)", "country_code" => "DE"],
        ["city" => "Stuttgart", "country_code" => "DE"],
        ["city" => "Santa Rosa", "country_code" => "US"],
        ["city" => "St Thomas Island", "country_code" => "VI"],
        ["city" => "Stavropol", "country_code" => "RU"],
        ["city" => "St Croix Island", "country_code" => "VI"],
        ["city" => "Surabaya", "country_code" => "ID"],
        ["city" => "Lamezia Terme", "country_code" => "IT"],
        ["city" => "Hailey (Sun Valley)", "country_code" => "US"],
        ["city" => "Suva", "country_code" => "FJ"],
        ["city" => "Sioux City", "country_code" => "US"],
        ["city" => "Stavanger", "country_code" => "NO"],
        ["city" => "Sevilla", "country_code" => "ES"],
        ["city" => "Ekaterinburg", "country_code" => "RU"],
        ["city" => "Shantou", "country_code" => "CN"],
        ["city" => "Newburgh", "country_code" => "US"],
        ["city" => "St Maarten", "country_code" => "AN"],
        ["city" => "Srinagar", "country_code" => "IN"],
        ["city" => "Sydney (RAAF base)", "country_code" => "AU"],
        ["city" => "Sydney (Bankstown)", "country_code" => "AU"],
        ["city" => "Sydney (Palm Beach)", "country_code" => "AU"],
        ["city" => "Sydney (Rose Bay)", "country_code" => "AU"],
        ["city" => "Sydney", "country_code" => "AU"],
        ["city" => "Sydney", "country_code" => "AU"],
        ["city" => "Sydney", "country_code" => "AU"],
        ["city" => "Syracuse", "country_code" => "US"],
        ["city" => "Sanya", "country_code" => "CN"],
        ["city" => "Shiraz", "country_code" => "IR"],
        ["city" => "Salzburg", "country_code" => "AT"],
        ["city" => "Skukuza", "country_code" => "ZA"],
        ["city" => "Shenzhen", "country_code" => "CN"],
        ["city" => "Tagbilaran", "country_code" => "PH"],
        ["city" => "Tanna", "country_code" => "VU"],
        ["city" => "Takamatsu", "country_code" => "JP"],
        ["city" => "Qingdao", "country_code" => "CN"],
        ["city" => "Tashkent", "country_code" => "UZ"],
        ["city" => "Tbilisi", "country_code" => "GE"],
        ["city" => "Nukualofa", "country_code" => "TO"],
        ["city" => "Tennant Creek", "country_code" => "AU"],
        ["city" => "Tenerife (North Airport)", "country_code" => "ES"],
        ["city" => "Tenerife", "country_code" => "ES"],
        ["city" => "Tacna", "country_code" => "PE"],
        ["city" => "Trat Airport", "country_code" => "TH"],
        ["city" => "Tongren", "country_code" => "CN"],
        ["city" => "Telluride", "country_code" => "US"],
        ["city" => "Podorica", "country_code" => "YU"],
        ["city" => "Kuala Terengganu", "country_code" => "MY"],
        ["city" => "Tirgu Mures", "country_code" => "RO"],
        ["city" => "Thanh Hoa", "country_code" => "VN"],
        ["city" => "Teresina", "country_code" => "BR"],
        ["city" => "Tehran", "country_code" => "IR"],
        ["city" => "Sukhothai", "country_code" => "TH"],
        ["city" => "Tirana", "country_code" => "AL"],
        ["city" => "Taif", "country_code" => "SA"],
        ["city" => "Tripoli", "country_code" => "LY"],
        ["city" => "Thursday Island", "country_code" => "AU"],
        ["city" => "Timaru", "country_code" => "NZ"],
        ["city" => "Tivat", "country_code" => "YU"],
        ["city" => "Tyumen", "country_code" => "RU"],
        ["city" => "Tokushima", "country_code" => "JP"],
        ["city" => "Turku", "country_code" => "FI"],
        ["city" => "Tallahassee", "country_code" => "US"],
        ["city" => "Toulouse (Blagnac)", "country_code" => "FR"],
        ["city" => "Tel Aviv (Sde Dov)", "country_code" => "IL"],
        ["city" => "Tel Aviv", "country_code" => "IL"],
        ["city" => "Tampere", "country_code" => "FI"],
        ["city" => "Tamworth", "country_code" => "AU"],
        ["city" => "Jinan", "country_code" => "CN"],
        ["city" => "Tanegashima", "country_code" => "JP"],
        ["city" => "Tangier", "country_code" => "MA"],
        ["city" => "Tomsk", "country_code" => "RU"],
        ["city" => "Toledo", "country_code" => "US"],
        ["city" => "Tampa", "country_code" => "US"],
        ["city" => "Taipei", "country_code" => "TW"],
        ["city" => "Tarapoto", "country_code" => "PE"],
        ["city" => "Tom Price", "country_code" => "AU"],
        ["city" => "Taramajima", "country_code" => "JP"],
        ["city" => "Tauranga", "country_code" => "NZ"],
        ["city" => "Bristol", "country_code" => "US"],
        ["city" => "Turin", "country_code" => "IT"],
        ["city" => "Taree", "country_code" => "AU"],
        ["city" => "Trieste", "country_code" => "IT"],
        ["city" => "Trujillo", "country_code" => "PE"],
        ["city" => "Thiruvananthapurm", "country_code" => "IN"],
        ["city" => "Tarawa", "country_code" => "KI"],
        ["city" => "Tiruchirapally", "country_code" => "IN"],
        ["city" => "Tianjin", "country_code" => "CN"],
        ["city" => "Timisoara", "country_code" => "RO"],
        ["city" => "Townsville", "country_code" => "AU"],
        ["city" => "Tulsa", "country_code" => "US"],
        ["city" => "Tunis", "country_code" => "TN"],
        ["city" => "Taupo", "country_code" => "NZ"],
        ["city" => "Tucson", "country_code" => "US"],
        ["city" => "Tucson", "country_code" => "US"],
        ["city" => "Tabuk", "country_code" => "SA"],
        ["city" => "Traverse City", "country_code" => "US"],
        ["city" => "Tangshan Sannuhe", "country_code" => "CN"],
        ["city" => "Toowoomba", "country_code" => "AU"],
        ["city" => "Shuinan", "country_code" => "TW"],
        ["city" => "Tunxi", "country_code" => "CN"],
        ["city" => "Taiyuan", "country_code" => "CN"],
        ["city" => "Tokyo (Narita)", "country_code" => "JP"],
        ["city" => "Tokyo (Haneda)", "country_code" => "JP"],
        ["city" => "Tyler", "country_code" => "US"],
        ["city" => "Knoxville", "country_code" => "US"],
        ["city" => "Ube", "country_code" => "JP"],
        ["city" => "Utica", "country_code" => "US"],
        ["city" => "Uberlandia", "country_code" => "BR"],
        ["city" => "Udaipur", "country_code" => "IN"],
        ["city" => "Queenstown (AU)", "country_code" => "AU"],
        ["city" => "Ufa", "country_code" => "RU"],
        ["city" => "Urgench", "country_code" => "UZ"],
        ["city" => "Quibdo", "country_code" => "CO"],
        ["city" => "Quito", "country_code" => "EC"],
        ["city" => "Ust Kamenogorsk", "country_code" => "KZ"],
        ["city" => "Ulei", "country_code" => "VU"],
        ["city" => "Ulundi", "country_code" => "ZA"],
        ["city" => "Ulaanbaatar", "country_code" => "MN"],
        ["city" => "Quilpie", "country_code" => "AU"],
        ["city" => "Ujung Pandang", "country_code" => "ID"],
        ["city" => "Urumqi", "country_code" => "CN"],
        ["city" => "Ushuaia", "country_code" => "AR"],
        ["city" => "Koh Samui", "country_code" => "TH"],
        ["city" => "Udon Thani", "country_code" => "TH"],
        ["city" => "Upington", "country_code" => "ZA"],
        ["city" => "Umtata", "country_code" => "ZA"],
        ["city" => "Ulan Ude", "country_code" => "RU"],
        ["city" => "Yuzhno Sakhalinsk", "country_code" => "RU"],
        ["city" => "Vaasa", "country_code" => "FI"],
        ["city" => "Suavanao", "country_code" => "SB"],
        ["city" => "Varna", "country_code" => "BG"],
        ["city" => "Vavau", "country_code" => "TO"],
        ["city" => "Venice", "country_code" => "IT"],
        ["city" => "Veracruz", "country_code" => "MX"],
        ["city" => "Victoria Falls", "country_code" => "ZW"],
        ["city" => "Vigo", "country_code" => "ES"],
        ["city" => "Vienna", "country_code" => "AT"],
        ["city" => "Vinh", "country_code" => "VN"],
        ["city" => "Vitoria", "country_code" => "ES"],
        ["city" => "Vitoria", "country_code" => "BR"],
        ["city" => "Valencia", "country_code" => "ES"],
        ["city" => "Port Vila", "country_code" => "VU"],
        ["city" => "Valladolid", "country_code" => "ES"],
        ["city" => "Vilnius", "country_code" => "LT"],
        ["city" => "Varanasi", "country_code" => "IN"],
        ["city" => "Volgograd", "country_code" => "RU"],
        ["city" => "Volos", "country_code" => "GR"],
        ["city" => "Ft Walton Beach", "country_code" => "US"],
        ["city" => "Verona", "country_code" => "IT"],
        ["city" => "Vientiane", "country_code" => "LA"],
        ["city" => "Valledupar", "country_code" => "CO"],
        ["city" => "Villavicencio", "country_code" => "CO"],
        ["city" => "Vladivostok", "country_code" => "RU"],
        ["city" => "Wanganui", "country_code" => "NZ"],
        ["city" => "Washington (US)", "country_code" => "US"],
        ["city" => "Washington DC (Reagan)", "country_code" => "US"],
        ["city" => "Washington DC (Dulles Intl)", "country_code" => "US"],
        ["city" => "Warsaw", "country_code" => "PL"],
        ["city" => "Castro", "country_code" => "CL"],
        ["city" => "Windhoek", "country_code" => "NA"],
        ["city" => "Weipa", "country_code" => "AU"],
        ["city" => "Wagga Wagga", "country_code" => "AU"],
        ["city" => "Walgett", "country_code" => "AU"],
        ["city" => "Whakatane", "country_code" => "NZ"],
        ["city" => "Wick", "country_code" => "GB"],
        ["city" => "Winton", "country_code" => "AU"],
        ["city" => "Wanaka", "country_code" => "NZ"],
        ["city" => "Miles", "country_code" => "AU"],
        ["city" => "Wellington", "country_code" => "NZ"],
        ["city" => "Wallis Island", "country_code" => "WF"],
        ["city" => "Mount Keith", "country_code" => "AU"],
        ["city" => "Windorah", "country_code" => "AU"],
        ["city" => "Wenzhou", "country_code" => "CN"],
        ["city" => "Wollongong", "country_code" => "AU"],
        ["city" => "Whangarei", "country_code" => "NZ"],
        ["city" => "Wrangell", "country_code" => "US"],
        ["city" => "Washington (County)", "country_code" => "US"],
        ["city" => "Westport", "country_code" => "NZ"],
        ["city" => "Toowoomba (Brisbane West Wellcamp)", "country_code" => "AU"],
        ["city" => "Wuhan", "country_code" => "CN"],
        ["city" => "Wuxi", "country_code" => "CN"],
        ["city" => "Walvis Bay", "country_code" => "NA"],
        ["city" => "Whyalla", "country_code" => "AU"],
        ["city" => "Christmas Island", "country_code" => "CX"],
        ["city" => "Xiamen", "country_code" => "CN"],
        ["city" => "Jerez Frontera", "country_code" => "ES"],
        ["city" => "Thargomindah", "country_code" => "AU"],
        ["city" => "Xuzhou", "country_code" => "CN"],
        ["city" => "Chillan", "country_code" => "CL"],
        ["city" => "Yakutat", "country_code" => "US"],
        ["city" => "Sault Ste Marie", "country_code" => "CA"],
        ["city" => "Banff", "country_code" => "CA"],
        ["city" => "Bagotville", "country_code" => "CA"],
        ["city" => "Brandon", "country_code" => "CA"],
        ["city" => "Nanaimo", "country_code" => "CA"],
        ["city" => "Castlegar", "country_code" => "CA"],
        ["city" => "Deer Lake", "country_code" => "CA"],
        ["city" => "Edmonton", "country_code" => "CA"],
        ["city" => "Edmonton", "country_code" => "CA"],
        ["city" => "Fredericton", "country_code" => "CA"],
        ["city" => "Kingston", "country_code" => "CA"],
        ["city" => "Hamilton", "country_code" => "CA"],
        ["city" => "Halifax", "country_code" => "CA"],
        ["city" => "Kamloops", "country_code" => "CA"],
        ["city" => "Kitchener", "country_code" => "CA"],
        ["city" => "Yakima", "country_code" => "US"],
        ["city" => "Yakutsk", "country_code" => "RU"],
        ["city" => "Kelowna", "country_code" => "CA"],
        ["city" => "Fort Mcmurray", "country_code" => "CA"],
        ["city" => "Montreal (Dorval)", "country_code" => "CA"],
        ["city" => "Montreal", "country_code" => "CA"],
        ["city" => "Yanbu", "country_code" => "SA"],
        ["city" => "Yantai", "country_code" => "CN"],
        ["city" => "Ottawa", "country_code" => "CA"],
        ["city" => "Prince Rupert", "country_code" => "CA"],
        ["city" => "Powell River", "country_code" => "CA"],
        ["city" => "Quebec", "country_code" => "CA"],
        ["city" => "Windsor", "country_code" => "CA"],
        ["city" => "Moncton", "country_code" => "CA"],
        ["city" => "Comox", "country_code" => "CA"],
        ["city" => "Regina", "country_code" => "CA"],
        ["city" => "Thunder Bay", "country_code" => "CA"],
        ["city" => "Grande Prairie", "country_code" => "CA"],
        ["city" => "Gander", "country_code" => "CA"],
        ["city" => "Sydney (CA)", "country_code" => "CA"],
        ["city" => "Sudbury", "country_code" => "CA"],
        ["city" => "Saint John", "country_code" => "CA"],
        ["city" => "Toronto", "country_code" => "CA"],
        ["city" => "Toronto", "country_code" => "CA"],
        ["city" => "Timmins", "country_code" => "CA"],
        ["city" => "Yuma", "country_code" => "US"],
        ["city" => "Rouyn", "country_code" => "CA"],
        ["city" => "Vancouver (Harbour)", "country_code" => "CA"],
        ["city" => "Vancouver (Boundary Bay)", "country_code" => "CA"],
        ["city" => "Vancouver", "country_code" => "CA"],
        ["city" => "Winnipeg", "country_code" => "CA"],
        ["city" => "Whistler", "country_code" => "CA"],
        ["city" => "Cranbrook", "country_code" => "CA"],
        ["city" => "Saskatoon", "country_code" => "CA"],
        ["city" => "Medicine Hat", "country_code" => "CA"],
        ["city" => "Fort St John", "country_code" => "CA"],
        ["city" => "Prince George", "country_code" => "CA"],
        ["city" => "Terrace", "country_code" => "CA"],
        ["city" => "London (CA)", "country_code" => "CA"],
        ["city" => "Abbotsford", "country_code" => "CA"],
        ["city" => "Whitehorse", "country_code" => "CA"],
        ["city" => "North Bay", "country_code" => "CA"],
        ["city" => "Calgary", "country_code" => "CA"],
        ["city" => "Smithers", "country_code" => "CA"],
        ["city" => "Penticton", "country_code" => "CA"],
        ["city" => "Charlottetown", "country_code" => "CA"],
        ["city" => "Victoria", "country_code" => "CA"],
        ["city" => "St Johns", "country_code" => "CA"],
        ["city" => "Yellowknife", "country_code" => "CA"],
        ["city" => "Sarnia", "country_code" => "CA"],
        ["city" => "Sept Iles", "country_code" => "CA"],
        ["city" => "Zagreb", "country_code" => "HR"],
        ["city" => "Valdivia", "country_code" => "CL"],
        ["city" => "Zaragoza", "country_code" => "ES"],
        ["city" => "Biloela (Thangool)", "country_code" => "AU"],
        ["city" => "Zacetecas", "country_code" => "MX"],
        ["city" => "Temuco", "country_code" => "CL"],
        ["city" => "Zihuatejo", "country_code" => "MX"],
        ["city" => "Manzanillo", "country_code" => "MX"],
        ["city" => "Newman", "country_code" => "AU"],
        ["city" => "Osorno", "country_code" => "CL"],
        ["city" => "Pucon", "country_code" => "CL"],
        ["city" => "Queenstown", "country_code" => "NZ"],
        ["city" => "Zweibruecken", "country_code" => "DE"],
        ["city" => "Zurich", "country_code" => "CH"],
        ["city" => "Zakinthos Island", "country_code" => "GR"],
        ["city" => "Al Ain Bus Station", "country_code" => "AE"],
        ["city" => "Abu Dhabi Bus Station", "country_code" => "AE"],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->cities as $city) {
            $country_code = array_get($city, 'country_code');
            $city_name = array_get($city, 'city');
            $country = Country::where('iso_alpha_2', $country_code)->first();
            if (!is_null($country)) {
                $country->cities()->save(new City([
                    'name' => $city_name
                ]));
            } else {
                dump("{$country_code} not found");
            }
        }
    }
}
